services:
    weather-bot-backend:
        environment:
            - LOG_DIR=/home/logs
        build: .
        ports:
            - '3123:3123'
        volumes:
            - ./logs:/home/logs
        restart: unless-stopped
