// TODO: Add more to the lexicon as needed by the limitations of the current model
export const cities = {
    casablanca: 'Place',
    prague: 'Place',
    brno: 'Place',
    ostrava: 'Place',
    plzen: 'Place',
    liberec: 'Place',
    olomouc: 'Place',
    ceske_budejovice: 'Place',
    usti_nad_labem: 'Place',
    hradec_kralove: 'Place',
    pardubice: 'Place',
    zlin: 'Place',
    havirov: 'Place',
    kladno: 'Place',
    most: 'Place',
    opava: 'Place',
    frydek_mistek: 'Place',
    karvina: 'Place',
    jihlava: 'Place',
    teplice: 'Place',
    chomutov: 'Place',
}
